//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleyee
    {
        public int EmpleyeeID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SellID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sell Sell { get; set; }
    }
}
